name: build_test
on:
  push:
    branches:
      - main
jobs:
    full-test:
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v4
          with:
            clean: false
            submodules: 'recursive'
        - uses: webfactory/ssh-agent@v0.5.4
          with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        - name: Run build
          timeout-minutes: 600
          run: |
            docker run --rm \
                 -v $SSH_AUTH_SOCK:/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent \
                 -e GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" \
                 -v ${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE} \
                 cuaesd/aesd-autotest:24-assignment6-yocto \
                 --workdir=${GITHUB_WORKSPACE} \
                 ./build.sh
        - name: Cleanup
          if: always()
          run: |
            ssh-add -D
        - name: Run full test
          timeout-minutes: 15
          run: |
            docker run --rm \
              -v ${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE} \
              cuaesd/aesd-autotest:assignment6-yocto \
              --workdir=${GITHUB_WORKSPACE} \
              ./full-test.sh